// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA32jXIyc72d2QIse1chkTjCeC__d0gPsg',
    appId: '1:141070963911:web:124341cd74a88ca4cb5ae2',
    messagingSenderId: '141070963911',
    projectId: 'fluke-db',
    authDomain: 'fluke-db.firebaseapp.com',
    storageBucket: 'fluke-db.appspot.com',
    measurementId: 'G-4HCHFSTCXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32jXIyc72d2QIse1chkTjCeC__d0gPsg',
    appId: '1:141070963911:android:09398d6028212ba7cb5ae2',
    messagingSenderId: '141070963911',
    projectId: 'fluke-db',
    storageBucket: 'fluke-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPuOUwjTZ41sEFjxsDxLoflSwVCcbir2w',
    appId: '1:141070963911:ios:df3bc0439501dd4bcb5ae2',
    messagingSenderId: '141070963911',
    projectId: 'fluke-db',
    storageBucket: 'fluke-db.appspot.com',
    androidClientId: '141070963911-0qksepvpk7hoo5csnqvgnkmj2ggpha53.apps.googleusercontent.com',
    iosClientId: '141070963911-balou9ptqr22m7gkv7o46odlsq0f15n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flukepro',
  );
}
